common/schemaGraph/state/interfaces.ts, common/schemaGraph/state/query.ts, web/src/state/models/dataview/index.ts
Once edgedb/edgedb#3735 lands, this will fix #13.
=> Use from_alias field to skip aliases

shared/common/schemaData/queries.ts, shared/studio/components/databasePage/databasePage.module.scss, shared/studio/components/databasePage/index.tsx, shared/studio/package.json, shared/studio/tabs/dataview/dataInspector.tsx, shared/studio/tabs/dataview/index.tsx, shared/studio/tabs/dataview/state/edits.ts, shared/studio/tabs/dataview/state/index.ts, shared/studio/tabs/schema/renderers/object.tsx, shared/studio/tabs/schema/state/textView.ts, shared/studio/tabs/schema/textView.tsx, yarn.lock
Fixes: #38, #37, and firefox part of #34
=> Fix some bugs

shared/common/ui/select/select.module.scss, shared/inspector/v2/buildItem.tsx, shared/inspector/v2/state.ts, shared/studio/components/dataEditor/dataEditor.module.scss, shared/studio/components/dataEditor/index.tsx, shared/studio/tabs/dataview/dataview.module.scss, shared/studio/tabs/dataview/index.tsx, shared/studio/tabs/dataview/state/edits.ts, shared/studio/tabs/dataview/state/index.ts, shared/studio/tabs/repl/paramEditor/paramEditor.module.scss, shared/studio/tabs/repl/repl.module.scss
Fixes https://github.com/edgedb/edgedb/issues/4211 and https://github.com/edgedb/edgedb/issues/4280
=> Various small fixes

shared/studio/components/sessionState/index.tsx, shared/studio/components/sessionState/sessionState.module.scss, shared/studio/state/connection.ts, shared/studio/tabs/dataview/state/index.ts, shared/studio/tabs/repl/index.tsx, shared/studio/tabs/repl/replHistoryCell/index.tsx, shared/studio/tabs/repl/replHistoryCell/replHistoryCell.module.scss, shared/studio/tabs/repl/state/index.ts
Fixes #48 and partly fixes #49
=> Make 'Disable Access Policies' a global option + add note to repl result

shared/studio/tabs/dataview/dataInspector.tsx
=> Fix editing of string fields on inserted objects in data explorer

shared/common/schemaData/index.ts, shared/studio/tabs/dataview/state/index.ts, shared/studio/tabs/schema/renderers/extension.tsx, shared/studio/tabs/schema/renderers/pointer.tsx, shared/studio/tabs/schema/renderers/utils.tsx, shared/studio/tabs/schema/state/textView.ts
=> Fix union type link targets in data viewer

shared/studio/tabs/dataview/dataInspector.tsx, shared/studio/tabs/dataview/state/edits.ts, shared/studio/tabs/dataview/state/index.ts
=> Further fixes for union links handling in data explorer

shared/studio/tabs/repl/index.tsx, shared/studio/tabs/repl/repl.module.scss
Depends on [113](https://github.com/edgedb/edgedb-ui/issues/113).
[Figma](https://www.figma.com/file/430gInXr2xbFqBOLTCmpHJ/Cloud_UI?t=ws5PX45PECxEQMG3-0)
Minor styles' updates.
=> 113: REPL update welcome text styles.

shared/studio/tabs/dataview/dataInspector.module.scss, web/src/app.module.scss
Depends on [116](https://github.com/edgedb/edgedb-ui/issues/116).
=> 116: Update buttons' text color

shared/codeEditor/codeEditor.module.scss, shared/codeEditor/theme.ts, shared/studio/tabs/queryEditor/repl.module.scss, web/src/app.module.scss
Depends on [114](https://github.com/edgedb/edgedb-ui/issues/114).
=> 114: Change repl cursor color

shared/studio/tabs/dataview/state/index.ts
See: https://discord.com/channels/841451783728529451/1065785389291425832/1067127318138589245
=> Fix data view crash which occurs sometimes when data is refreshed

shared/studio/components/databasePage/databasePage.module.scss
Depends on [132](https://github.com/edgedb/edgedb-ui/issues/132).
=> 132: Update tooltip font styles.

shared/studio/tabs/dataview/dataview.module.scss, shared/studio/tabs/dataview/index.tsx
Depends on [131](https://github.com/edgedb/edgedb-ui/issues/131).
=> 131: Fix dataviewer top bar.

shared/studio/state/sessionState.ts
=> 140: Update session state update cases.

shared/schemaGraph/components/schemaGraph/SchemaNodeObject.tsx, shared/schemaGraph/components/schemaGraph/index.tsx, shared/schemaGraph/state/index.ts
=> 115: Update schema with deselect functionality.

shared/common/ui/select/select.module.scss, shared/common/ui/toggleSwitch/toggleSwitch.module.scss, shared/studio/components/sessionState/sessionState.module.scss, shared/studio/tabs/schema/textView.module.scss, web/src/app.module.scss
Solves #118 .
I updated colors but there are still some things that does not have design in Figma for different states, or same states in different components have different designs. I'm a confused about what end result should be.
This is Figma. I don't understand why different UIs in the left and right columns regarding true/false buttons. 
And also is there a design difference between active/passive states of these buttons or not.
@shougan
=> 118: Fix colors.

shared/schemaGraph/state/graph.ts, shared/studio/tabs/queryEditor/history.tsx, shared/studio/tabs/queryEditor/index.tsx, shared/studio/tabs/queryEditor/repl.module.scss, shared/studio/tabs/queryEditor/state/index.ts, web/tests/clientSettings.test.ts, web/tests/queryEditor.test.ts, yarn.lock
=> 153 new history UI

shared/codeEditor/index.tsx
=> Fix crash when error highlight range is empty

shared/inspector/buildScalar.tsx
=> Fix JSON pretty printing when string ends with backslashes

shared/studio/components/visualQuerybuilder/index.tsx, shared/studio/components/visualQuerybuilder/queryBuilder.module.scss
=> 172: Add copy btn to copy query from visual query builder

shared/studio/tabs/dataview/dataInspector.tsx, shared/studio/tabs/dataview/dataview.module.scss, shared/studio/tabs/dataview/index.tsx, shared/studio/tabs/dataview/state/edits.ts, shared/studio/tabs/dataview/state/index.ts, web/tests/_utils.ts, web/tests/dataViewer.test.ts
Fixes #190, #189, #186 and #185
=> Dataview fixes

shared/inspector/buildScalar.tsx
=> Fix float32 rendering

shared/codeEditor/completions.ts, shared/studio/components/objectTypeSelect/index.tsx, shared/studio/components/visualQuerybuilder/index.tsx
=> Nested module fixes

shared/common/hooks/useTooltips.tsx, shared/common/ui/verticalTabBar/index.tsx, shared/common/ui/verticalTabBar/verticalTabBar.module.scss, shared/studio/components/headerNav/elements.tsx, web/src/app.tsx
=> Show left navbar items below top navbar dropdown

shared/studio/icons/index.tsx, shared/studio/tabs/auth/authAdmin.module.scss, shared/studio/tabs/auth/index.tsx
Depends on https://github.com/edgedb/edgedb.com/pull/717
=> Add note linking to auth docs to auth admin page

shared/studio/tabs/auth/authAdmin.module.scss, shared/studio/tabs/auth/index.tsx
=> Add useful auth urls to auth admin screen

shared/studio/components/headerNav/headerNav.module.scss, shared/studio/components/objectTypeSelect/index.tsx, shared/studio/components/visualQuerybuilder/index.tsx, shared/studio/tabs/dataview/dataInspector.tsx, shared/studio/tabs/dataview/state/index.ts, shared/studio/tabs/queryEditor/paramEditor/index.tsx
=> Small fixes

shared/studio/tabs/dataview/index.tsx, shared/studio/tabs/dataview/state/index.ts
=> Strip comments from dataview filter

shared/studio/tabs/dataview/state/index.ts
=> Fix query gen for dataview when link targeting object type with access policy shares name with computed link

shared/common/ui/icons/index.tsx, shared/common/ui/mobile/roundButton/index.tsx, shared/common/ui/mobile/roundButton/roundButton.module.scss, shared/studio/state/connection.ts, shared/studio/tabs/dataview/state/index.ts, shared/studio/tabs/queryEditor/index.tsx, shared/studio/tabs/queryEditor/state/index.ts, shared/studio/tabs/repl/index.tsx, shared/studio/tabs/repl/repl.module.scss, shared/studio/tabs/repl/state/index.ts
Depends on https://github.com/edgedb/edgedb-js/pull/707
=> Query cancellation

shared/studio/tabs/auth/authAdmin.module.scss, shared/studio/tabs/auth/index.tsx, shared/studio/tabs/auth/loginuipreview.module.scss, shared/studio/tabs/auth/state/index.tsx
Docs: https://www.edgedb.com/docs/guides/auth/index#allowed-redirect-urls
=> Add auth config for allowed_redirect_urls

shared/studio/tabs/dataview/state/index.ts
See https://discord.com/channels/841451783728529451/849377751370432573/1171745773361307701
=> Fix dataview count query to behave the same data fetching query when filters are applied

shared/common/schemaData/index.ts, shared/common/schemaData/queries.ts, shared/studio/state/database.ts, shared/studio/tabs/dataview/dataInspector.module.scss, shared/studio/tabs/dataview/dataInspector.tsx, shared/studio/tabs/dataview/index.tsx, shared/studio/tabs/dataview/state/index.ts
=> Don't query secret properties in dataview + make config types in dataview readonly

shared/common/components/dataGrid/dataGrid.module.scss, shared/common/components/dataGrid/index.tsx, shared/common/components/dataGrid/state.ts, shared/common/components/dataGrid/utils.ts, shared/common/components/resultGrid/index.tsx, shared/common/components/resultGrid/resultGrid.module.scss, shared/common/components/resultGrid/state.ts, shared/common/newui/icons/index.tsx, shared/common/newui/modal/index.tsx, shared/common/newui/modal/modal.module.scss, shared/common/newui/theme.module.scss, shared/common/styles.scss, shared/inspector/buildScalar.tsx, shared/studio/components/dataEditor/dataEditor.module.scss, shared/studio/tabs/dataview/dataInspector.module.scss, shared/studio/tabs/dataview/dataInspector.tsx, shared/studio/tabs/dataview/dataview.module.scss, shared/studio/tabs/dataview/editsModal.module.scss, shared/studio/tabs/dataview/fieldConfig.module.scss, shared/studio/tabs/dataview/fieldConfig.tsx, shared/studio/tabs/dataview/index.tsx, shared/studio/tabs/dataview/reviewEditsModal.tsx, shared/studio/tabs/dataview/state/edits.ts, shared/studio/tabs/dataview/state/index.ts, web/tests/dataViewer.test.ts
Fixes some issues in https://github.com/edgedb/edgedb-ui/issues/331
Updates to data tab:
- add column select/hiding + re-ordering + pinning
- add refresh data button
- updates to overall styling
- Todo: fix things on mobile
=> Update data tab design + add column hiding / reordering / pinning

shared/inspector/state.ts, shared/studio/tabs/queryEditor/state/index.ts, shared/studio/tabs/repl/state/index.ts
Fixes #360 + also fixes copying in history results affected by bug
=> Fix copying results in query editor when implicit limit is disabled

shared/studio/state/connection.ts
=> For readonly queries default to use 'repeatable read' isolation

shared/studio/state/connection.ts, shared/studio/tabs/ai/state/index.ts, shared/studio/tabs/auth/state/index.tsx
See separate commits
Fixes https://github.com/geldata/gel/issues/8533
=> Yet more fixes

shared/studio/state/connection.ts, shared/studio/state/database.ts, shared/studio/state/instance.ts, shared/studio/tabs/ai/state/index.ts, shared/studio/tabs/ai/state/rag.ts, shared/studio/tabs/dataview/state/index.ts, shared/studio/tabs/repl/state/commands.ts, web/src/state/models/app.ts
Add query retries for network failures and other retryable errors when safe, and improve handling of token expiry, to hopefully resolve/improve some issues in cloud ui.
=> Refactor connection handling

shared/codeEditor/codeEditor.module.scss, shared/codeEditor/index.tsx, shared/studio/state/connection.ts, shared/studio/tabs/queryEditor/index.tsx, shared/studio/tabs/queryEditor/queryeditor.module.scss, shared/studio/tabs/queryEditor/state/index.ts, shared/studio/tabs/repl/index.tsx, shared/studio/tabs/repl/repl.module.scss, shared/studio/tabs/repl/state/index.ts, shared/studio/utils/extractErrorDetails.ts, web/tests/queryEditor.spec.ts, web/tests/repl.spec.ts
=> Show query warnings
