shared/inspector/v2/inspector.module.scss, shared/studio/tabs/dataview/dataInspector.module.scss, shared/studio/tabs/dataview/dataInspector.tsx
This is a temporary (partial) fix for #41/#64. In the future I'm thinking we should implement a more spreadsheet like selection behaviour, where you can select cells/ranges of cells, and there be a popup contexual ui with structured copy options (eg. copy as table, copy as json, copy as csv/tsv). This is also needed for the planned 'extended dataviewers'.
=> Allow text selection in dataview

shared/codeEditor/completions.ts, shared/inspector/v2/buildItem.tsx, shared/inspector/v2/buildScalar.tsx, shared/inspector/v2/index.tsx, shared/inspector/v2/inspector.module.scss, shared/inspector/v2/renderJsonResult.ts, shared/inspector/v2/state.ts, shared/inspector/v2/styles.d.ts, shared/inspector/v2/tsconfig.json, shared/studio/state/settings.ts, shared/studio/tabs/repl/index.tsx, shared/studio/tabs/repl/replHistoryCell/index.tsx, shared/studio/tabs/repl/replHistoryCell/replHistoryCell.module.scss, shared/studio/tabs/repl/state/index.ts
Cherry picks following changes from repl redesign to 2.x:
- Add basic autocomplete support for `insert`, `update` and `delete`
- Allow selectively copying results from result inspector
- Save repl settings ('disable access policies', 'persist query') to localstorage
- Fix nested data loading in dataview when link is single (#68)
=> Repl updates

shared/inspector/buildScalar.tsx, shared/studio/tabs/dataview/dataInspector.module.scss, shared/studio/tabs/dataview/dataInspector.tsx, shared/studio/tabs/dataview/state/index.ts
Fixes #81
Truncating strings to 100 characters is done as an optimisation, so the data explorer doesn't load huge strings that mostly won't be seen in the ui. I overlooked that the ui needs to fetch the full string when editing, so now the full string is lazily fetched when the data editor is opened. Also strings that have been truncated are now indicated with `...`.
=> Lazy load truncated string data when opening edit popup in data view

shared/studio/tabs/dataview/state/edits.ts
=> In data editor codegen, ensure nested object type refs in updates/inserts are `detached` if parent is same type

shared/studio/tabs/dataview/state/edits.ts
Reported on discord: https://discord.com/channels/841451783728529451/841451783728529454/1054401499402350632
=> Fix bug preventing data explorer inserts when type has required computed link

shared/studio/components/headerTabs/index.tsx
Depends on [102](https://github.com/edgedb/edgedb-ui/issues/102).
The designs for this [Figma](https://www.figma.com/file/430gInXr2xbFqBOLTCmpHJ/Cloud_UI?node-id=1345%3A42275&t=EcpPdCxBEr31DTZG-0).
Here is the fix for the first check point: separators.
The fix is ​​inside the shared folder which is also used for the website application as far as I know.
=> Update separators icons to be smaller and tinier

shared/inspector/v2/index.tsx, shared/inspector/v2/state.ts
=> Fix collapsing/expanding inspector items when child items are multiline

shared/studio/tabs/dashboard/databaseDashboard.module.scss, shared/studio/tabs/dashboard/index.tsx
Depends on [102](https://github.com/edgedb/edgedb-ui/issues/102).
Query editor button is added on the dashboard.
On desktop it looks fine, but on smaller screens 4 buttons aren't nicely organised.
=> Add button for query editor on the dashboard.

shared/common/ui/select/select.module.scss, shared/studio/components/headerTabs/headerTab.module.scss, web/src/app.module.scss
Depends on [130](   git push --set-upstream origin 130-fix-topbar-dropdown-color).
=> 130: Add different color for dropdown item labels.

.github/workflows/ui_tests.yml, shared/common/schemaData/index.ts, shared/common/schemaData/queries.ts, shared/studio/idbStore/index.ts, shared/studio/state/database.ts, shared/studio/state/instance.ts, shared/studio/tabs/schema/renderers/global.tsx, shared/studio/tabs/schema/renderers/module.tsx, shared/studio/tabs/schema/renderers/object.tsx, shared/studio/tabs/schema/renderers/pointer.tsx, shared/studio/tabs/schema/renderers/utils.tsx
The longstanding `TypeError: undefined is not an object (evaluating 'e.name.localeCompare')` bug (#188, #187, #79, #34), appears to be caused by some kind of data corruption that I think is possibly a bug in safari when cyclic data is stored in indexeddb. So I'm hoping that the refactor in this PR, to store the flat introspection data in indexeddb before we cross reference types in it, will fix this bug.
Also update schema introspection and rendering to support the new mutation rewrites, triggers and access policy `errmessage` in 3.0, and update from `->` to `:` syntax.
=> Schema fixes

shared/studio/tabs/auth/authAdmin.module.scss, shared/studio/tabs/auth/index.tsx, shared/studio/tabs/auth/loginUIPreview.tsx, shared/studio/tabs/auth/state/index.tsx
We use these details in several places around the app now, so we should read and write the new values from the main `AuthConfig` object.
Note: the old app details in the `UIConfig` still exist, but we should consider them deprecated and ignore the existing values there.
---
As far as a deployment plan goes, I'm not sure how to make sure this gets sequenced correctly. It should only be merged once the server change that it depends on is merged, and it should not be backported to 4.x. I mostly did this work so I can actually test the server change, so apologies for the weird sequencing here.
=> Move app details to main AuthAdminState

shared/studio/tabs/auth/index.tsx, shared/studio/tabs/auth/loginUIPreview.tsx, shared/studio/tabs/auth/loginuipreview.module.scss, shared/studio/tabs/auth/state/index.tsx, yarn.lock
Depends on #306
~Todo: Update login UI preview to include webauthn option~
=> Add support for WebAuthn+magic link providers and update login ui preview

shared/studio/components/dataEditor/dataEditor.module.scss, shared/studio/components/dataEditor/editor.tsx, shared/studio/components/dataEditor/index.tsx, shared/studio/components/dataEditor/utils.ts, shared/studio/tabs/dataview/dataInspector.module.scss, shared/studio/tabs/dataview/dataInspector.tsx, shared/studio/tabs/dataview/editsModal.module.scss, shared/studio/tabs/dataview/reviewEditsModal.tsx, shared/studio/tabs/dataview/state/edits.ts, shared/studio/tabs/dataview/state/index.ts
Fixes #310
Input in datatable editor is now saved to pending edits by default when it closes (including clicking out of it), unless it's closed by the 'esc' key. This change also means invalid input can exist in the pending edits now, so styling added for invalid cells + checks added in commit changes modal.
=> Update behaviour of datatable editor to save input by default on closing

shared/common/ui/customScrollbar/index.tsx
Add bottom offset to the scroll bar and thumb.
=> Add top ignore scroll offset prop to the scroller

shared/studio/tabs/auth/index.tsx
Providers want an _exact_ match and we send the redirect_uri with the port when we make our authorize request to the IdP.
See https://github.com/edgedb/edgedb/blob/466120c00cc0165b02e06c9287e1dcb6cff6c79e/edb/server/protocol/protocol.pyx#L665-L669
=> Keep server port in base URL for redirect_uri

shared/studio/state/connection.ts, shared/studio/tabs/ai/state/rag.ts, shared/studio/tabs/auth/index.tsx, shared/studio/tabs/dataview/index.tsx, shared/studio/tabs/dataview/state/index.ts, shared/studio/tabs/repl/state/commands.ts, web/src/components/databasePage/index.tsx, web/src/components/instancePage/index.tsx
Fixes #352
Branch/database and object names can contain `/` characters which break routing whenever they appear in url paths in the ui or api urls. This PR adds url encoding of branch+object names where they appear in ui urls and in api calls to the server.
Depends on https://github.com/edgedb/edgedb/pull/7352
=> Properly url encode/decode branch names + object names whenever they're used in url paths

shared/studio/tabs/auth/loginuipreview.module.scss
Small fix for the Auth preview UI heading.
Before:
After:
(FWIW, I realise that two lines of the app name is not ideal anyway, and rather a rare scenario, but I figured it's still worth fixing.)
=> Update Auth preview form heading style

package.json, shared/codeEditor/index.tsx, shared/common/package.json, shared/common/schemaData/knownTypes.ts, shared/inspector/package.json, shared/schemaGraph/package.json, shared/studio/components/dataEditor/utils.ts, shared/studio/idbStore/index.ts, shared/studio/package.json, shared/studio/state/connection.ts, shared/studio/tabs/queryEditor/index.tsx, shared/studio/tabs/queryEditor/paramEditor/index.tsx, shared/studio/tabs/queryEditor/state/extractQueryParameters.ts, shared/studio/tabs/queryEditor/state/index.ts, shared/studio/tabs/queryEditor/state/parameters.ts, shared/studio/tabs/repl/commands.tsx, shared/studio/tabs/repl/index.tsx, shared/studio/tabs/repl/repl.module.scss, shared/studio/tabs/repl/state/commands.ts, shared/studio/tabs/repl/state/index.ts, shared/studio/tabs/repl/state/utils.ts, web/package.json, web/tests/repl.test.ts, yarn.lock
Depends on https://github.com/edgedb/edgedb-js/pull/1131 and https://github.com/edgedb/edgedb/pull/7991
=> Add support for sql queries in editor and repl

shared/studio/tabs/auth/authAdmin.module.scss, shared/studio/tabs/auth/providers.tsx, shared/studio/tabs/auth/shared.tsx, shared/studio/tabs/auth/smtp.tsx, shared/studio/tabs/auth/state/index.tsx, shared/studio/tabs/auth/webhooks.tsx
Adds support for the new SMTP config introduced in https://github.com/edgedb/edgedb/pull/7942.
@scotttrinh I'm not sure how the cloud magic smtp provider will be introspected, is it going to be a another type extending `cfg::EmailProvider` that won't be user configurable, or is it another `SMTPProviderConfig` which we have to make readonly in the UI?
~Also there's a new potential tripping hazard when updating an existing smtp provider, as I think we now have to update the whole config object, so that will reset the password every time unless you re-enter the password whenever you make a change.~
~Disabled editing of smtp configs for now.~
Re-enabled smtp config editing, but with a warning message if you don't re-enter the password.
=> Add support for new SMTP config schema

shared/common/branchGraph/branchGraph.module.scss, shared/common/branchGraph/diff.ts, shared/common/branchGraph/index.tsx, shared/common/branchGraph/layout.ts, shared/common/branchGraph/utils.ts, shared/studio/components/databasePage/index.tsx, shared/studio/components/modals/createBranch.tsx, shared/studio/state/database.ts, shared/studio/state/instance.ts, shared/studio/tabs/dashboard/index.tsx, shared/studio/tabs/repl/state/commands.ts, web/src/components/databasePage/index.tsx
- Automatically refresh branch graph using `last_migration` info
- Add sdl diff view to migrations panel
=> Branch graph update

shared/studio/components/dataEditor/parsers.ts
=> Add aliases for `cal::` input types to handle them moving to `std::cal::`

shared/studio/state/connection.ts, shared/studio/tabs/dataview/state/index.ts
The workaround query seems to be slow in 6 (regression?), so avoid it
when access policies are configured to be off.
=> Disable AP workarounds in DataInspector when `apply_access_policies` is off

shared/common/hooks/useKeyboardShortcut.ts, shared/common/ui/select/index.tsx, shared/common/ui/select/select.module.scss
Hi Gel team, 
This is an attempt at fixing one of my biggest pet peeves using the Data Explorer (which I use a lot):
Support for keyboard events to enable selecting a type after searching for it in the dropdown without the mouse.
In addition, I've added listeners for the CMD+P/Ctrl+P shortcut (à la VSCode) to open this dropdown.
A few notes:
- "enter" selects the highlighted type
- "esc" closes the dropdown
- both mouse over and keyboard navigation handle the same highlighted item
- highlighted item is kept stable even if the list updates (because of search filtering)
Let me know if that works for you. I would love to see this or a similar idea implemented in the UI.
Best
=> Keyboard (↑↓) support for type picker in DataExplorer view

shared/studio/components/modals/createBranch.tsx, shared/studio/state/connection.ts, shared/studio/state/database.ts, shared/studio/tabs/dashboard/index.tsx
The objects count query that the dashboard runs can be slow when the database contains a lot of objects, which blocks further queries in the UI until it's done. Since the object count on the dashboard is kind of just decorative we could get away with querying an approximate count, but we don't yet have a function for that: https://github.com/geldata/gel/issues/4164.
So instead cancel the count query when navigating away from the dashboard, and also add a connection pool to allow multiple simultaneous queries, as there's not really any reason to run most queries one at a time in the UI except for maybe schema introspection queries which some parts of the ui depend on to generate correct data fetching queries for example.
=> Fix dashboard causing queries to hang

shared/studio/state/connection.ts
Without this the object count on the dashboard page will incorrectly show fewer objects than actually exist if they are hidden by default by access polices.
=> When running internal queries that ignore session config, set `apply_access_policies` config to false
